- name: ensure nginx is at the latest version
  yum: name=nginx state=present

- name: write the nginx config file
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Create web root
  file: dest={{ root }} mode=755 state=directory owner=nginx group=nginx
  notify: reload nginx
- name: ensure nginx is running
  service: name=nginx state=restarted
